### ISSUE TITLE
Fix footer content centering in Nifas certificate template

### ISSUE THREAD

**Issue by KizaruZero** [KizaruZero/Backend-Olivia-HC#1]
## Problem
The footer content in the Sertifikat Penyelesaian Kunjungan Nifas template is not properly centered. Currently, the content is distributed across the width of the footer because of the `justify-content: space-between;` property applied to the `.footer-content` class.

As visible in the uploaded template image (<img alt="image1" width="887" src="https://github.com/user-attachments/assets/5178e4aa-024f-4731-8179-8119f5f5e598" />), the footer elements (dates on left, seal in middle, signature on right) don't align with the centered design of the rest of the certificate.

## Proposed Solution
Modify the CSS to center the footer content by:

1. Updating the `.footer-content` class to use center alignment
2. Adjusting the layout of the date, seal, and signature sections

## Code Changes

```css
/* Current CSS */
.footer-content {
    display: flex;
    justify-content: space-between;
    align-items: center;
}

/* Proposed changes */
.footer-content {
    display: flex;
    justify-content: center; /* Change from space-between to center */
    align-items: center;
    gap: 60px; /* Add spacing between elements */
}

/* Adjust width of sections to be more balanced */
.date-section, .signature-section {
    width: 25%; /* Reduce from 30% */
}

.seal-section {
    width: 20%; /* Reduce from 40% */
}
```

This change will center the three sections with appropriate spacing while maintaining their content alignment.

## Expected Result
The footer elements should be centered in the certificate layout, creating a more harmonious and balanced design that matches the centered layout of the certificate's other sections.
